{% set version = "0.3.1" %}

package:
  name: aospy
  version: {{ version }}

source:
  url: https://github.com/spencerahill/aospy/archive/v{{ version }}.tar.gz
  sha256: 57c16f869161f7a3c2fa754bbc2f576abae0caee682b2e9d5cc5ba1fa95bcfdb

build:
  number: 1000
  skip: True  # [py27]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.7
    - scipy >=0.16
    - pandas >=0.15.0
    - netcdf4 >=1.2
    - toolz >=0.7.2
    - dask >=0.14
    - distributed >=1.16.1
    - xarray >=0.9.1
    - cloudpickle >=0.2.1
    - cftime >=1.0.0

test:
  imports:
    - aospy
    - aospy.examples
    - aospy.test
    - aospy.test.data
    - aospy.test.data.objects
    - aospy.utils

about:
  home: https://github.com/spencerahill/aospy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Automated gridded climate data analysis and management'

  description: |
     A framework that enables automated calculations using gridded
     climate data. Following some basic description of where your data
     lives and defining any functions of variables stored in that data
     you want to compute, aospy enables you to fire off an arbitrary
     number of calculations using that data.
  doc_url: https://aospy.readthedocs.io/
  dev_url: https://github.com/spencerahill/aospy

extra:
  recipe-maintainers:
    - spencerahill
