travis:
  secure:
    BINSTAR_TOKEN: rFYqbk0GRS8d+F0pl9JHbzBB5/fjv1Km18plQLJTT0k6yq29cm66SxLAAm8RPdIEcXdOHk/KC26+MROzT6Bwte+nUvJBSmnhblvxsgejqZX98q1t1HsQIMVtZ4h8WIC/fcfAzLZdY4RQjAezl7DNqcF3xF4nl98ITZRj9syc3f8s6/iA3OzU6YcqVdHUYl/hfXTRuvdLIr1PHZozeE04/QfBMlo4du7dbLiAISVJhyPD66VhQ3qcJKCBje7hRWJkXLJi5YGCeVWjrzLQJh3N3/l5pGMuKzUEfUIuRKcME0fOLkBb5IPZl4+giL1YQUjMPSPWzeulSnqy9Ow/pZ+EQaGKc6EcsdmHJ6PAHOmynoXhN5UKoKx0sbz3qChhnbGzS1WDt6xoNSA41mq0aBQGARMJEmdMwLJycAENbP8sgdVpZxPelr0F2Jrn+9OObvGQ98G3N6eLvfD/SDyjDkCboKuuQzYuRqX2x4Rpv7F0+M9/JmsCwFZEWhzCHP9EK7xqMhvR+oDaNDKqaGiPCa+GyqS5v6+nmCH1PgaJ3ay2p004FFT2mRkuEN1o9ZV3/Zu0xVERMhhP74tEjCLgi72Px9faqSndyS/8Th7KSkCBJjW2hJnWe5jqST1eYWEXqdwdhAQxIZoppBTjUIaAs3/0YRePQKEWU0ChJhV7kW2EOG0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
