min_py_ver: '36'
max_py_ver: '37'
travis:
  secure:
    BINSTAR_TOKEN: lT/rBfIRP/avsDmn8nZGyHjPUMyZWTWilTgbQHWCwrspCA9mYO7uBICm9w35FwWyjwhXbe10VHDiZOPn8hAQFI9BhYkVIPVGqfulVOyFcU2nK3aqU+DZ0o6pwpGPEEWycjbe8RZGRwaOf04yNYHJt2bL65QaG72yi+k0EiHEM9m3YuSMKo7xfZ4/tJlT+XuaqhaZcn+IxBdvD3s5lpnc/n5EeGMs0EeBiWfGnVmUHwDxQm+5siaKJuX781h6UFfKOK5BgnnrSTqMhx1f5tInxKkrSusL6HqajmATK4HsbEsUmhd3aHpt8q65ZoxmSpVJiiBLswyCMlJy/XJQaPfe31cF77+C1OJUN7MBG7sd0CQKCSYZcJQ1r2A5iQcnn9pN6rEEXYcA/WfJhMIxwkcX9kW4Xd/7m53yu7rHGsxifE36nPn6+IfFeDARd/CviVTK+V1JVZxfCxhFin72xOAh9QSh+w+uqzevbKvlLhC5enLOrbitbHf6D15LZNjYlDLr16cWtPn7uuao3Mc9lNs3Uz/22b5ZBuZP9IVp1Vl6y5/c+WZjhQDsO5niDKnY/+58ixPO2wTzC6G8TZL3uiA2y6EczlPKeP7EmLABGF1HH2HkYd7jGFNRNzZbaHkqSnrduZUQKhbxpfu9yGFJm+BoeBYciIgK7mqFNFEDmNeHXHs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
